#!/usr/bin/env bash

search_dirs=(
    ~/work/catalogo_piani/root_backend
    ~/work/catalogo_piani/root_frontend
    ~/work/catalogo_piani
    ~/.config/
    ~/work
)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find "${search_dirs[@]}" -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected  
  if [[ $selected = *frontend/* ]]; then
    tmux split -vl 13 -d -t $selected_name -c $selected
  fi
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
  tmux switch-client -t $selected_name
  if [[ $selected = *frontend/* ]]; then
    tmux split -vl 13 -d -t $selected_name -c $selected
  fi
  exit 0
fi

tmux switch-client -t $selected_name
